# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/linuxdata/UTN/DDA/DDA-Entregas/TPLAB2/ENTREGABLE/work/Vivado/TPLAB_2/TPLAB_2.srcs/sources_1/ip/ila_0/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/linuxdata/UTN/DDA/DDA-Entregas/TPLAB2/ENTREGABLE/work/Vivado/TPLAB_2/TPLAB_2.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/linuxdata/UTN/DDA/DDA-Entregas/TPLAB2/ENTREGABLE/work/Vivado/TPLAB_2/TPLAB_2.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/linuxdata/UTN/DDA/DDA-Entregas/TPLAB2/ENTREGABLE/work/Vivado/TPLAB_2/TPLAB_2.gen/sources_1/ip/ila_0/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/linuxdata/UTN/DDA/DDA-Entregas/TPLAB2/ENTREGABLE/work/Vivado/TPLAB_2/TPLAB_2.srcs/sources_1/ip/ila_0/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/linuxdata/UTN/DDA/DDA-Entregas/TPLAB2/ENTREGABLE/work/Vivado/TPLAB_2/TPLAB_2.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/linuxdata/UTN/DDA/DDA-Entregas/TPLAB2/ENTREGABLE/work/Vivado/TPLAB_2/TPLAB_2.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/linuxdata/UTN/DDA/DDA-Entregas/TPLAB2/ENTREGABLE/work/Vivado/TPLAB_2/TPLAB_2.gen/sources_1/ip/ila_0/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
